name: Audit

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  audit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.2'

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.61

    - name: Unit tests
      run: make test
